Fix json-cfg syntax (#175)
This fixes the syntax for json-cfg when running --aws-managed-policies and --auth-details-file

Before this commit you would get an error similar to the following:

        jsoncfg.config_classes.JSONConfigNodeTypeError: Expected a ConfigJSONObject but found
        ConfigJSONScalar. You are trying to access the __contains__ magic method of a scalar
        config object.

It seems that instead of treating the json-cfg objects as hash's you're supposed to access keys
via attributes and use a method call when you want to convert it back into it's original form.

Passing an argument to this method call sets the default return, acting similar to:

        obj.get('key', default)